export const TEST_STATUS_ALL = "all";
export const TEST_STATUS_OK = "OK";
export const TEST_STATUS_SKIP = "SKIP";
export const TEST_STATUS_FAIL = "FAIL";
export const TEST_STATUS_UNKNOWN = "UNKNOWN";

export default {
    TEST_STATUS_ALL: TEST_STATUS_ALL,
    TEST_STATUS_OK: TEST_STATUS_OK,
    TEST_STATUS_SKIP: TEST_STATUS_SKIP,
    TEST_STATUS_FAIL: TEST_STATUS_FAIL,
    TEST_STATUS_UNKNOWN: TEST_STATUS_UNKNOWN,
}